library(violinplotter)
data(dummy_data)
str(dummy_data)
BEAUTY = violinplotter(formula = beauty ~ food*people, data=dummy_data)
FEET_QUALITY = violinplotter(formula = feet_quality ~ food*people, data=dummy_data)
