system("wget https://github.com/jeffersonfparil/violinplotter/archive/master.zip")
system("unzip master.zip")
setwd("violinplotter-master")
devtools::build()
setwd("..")
build_name = system("ls | grep violinplotter_*.tar.gz | tail -n1", intern=TRUE)
install.packages(build_name)
library(violinplotter)
